function p = init_clean_param_record(class_id, sample_index)

p = struct( ...
    'class_id',      int32(class_id), ...
    'sample_index',  int32(sample_index), ...
    'A',             NaN, ...
    'phi',           NaN, ...
    'f0',            NaN, ...
    'delta_f',       NaN, ...
    'sigma',         NaN, ...
    'K',             NaN, ...
    'alpha',         NaN, ...
    'tau_ns',        NaN, ...
    'f1',            NaN, ...
    'T',             NaN, ...
    'delta',         NaN, ...
    'alpha_tukey',   NaN, ...
    'fc',            NaN, ...
    'fm',            NaN, ...
    'theta',         NaN, ...
    'gamma',         NaN, ...
    'beta',          NaN, ...
    'beta2',         NaN, ...
    'phi_m1',        NaN, ...
    'phi_m2',        NaN, ...
    'fL',            NaN, ...
    'fH',            NaN, ...
    'bandwidth',     NaN, ...
    'Rc',            NaN, ...
    'filter_info',   struct(), ...
    'hop_info',      struct(), ...
    'ofdm_info',     struct(), ...
    'iofdm_info',     struct(), ...
    'pulse_info',    struct(), ...
    'srj_info',      struct(), ...
    'dftj_info',     struct(), ...
    'mbn_info',    struct(), ...
    'pgn_info',    struct(),...
    'burst_info',    struct(), ...
    'lims',          struct(), ...
    'units',         struct() ...
);

end