function x_clean = synthesize_clean_signal_class14(params, spec)
% SYNTHESIZE_CLEAN_SIGNAL_CLASS 14
% Chaotic FM Jammer
%
% The instantaneous frequency follows a deterministic chaotic trajectory
% generated by the logistic map. Integrating frequency to phase preserves
% temporal correlations in the output (non-zero bispectrum), which is the
% feature distinguishing this from any class 0-9 signal.
%
% Model:
%   y[n] = r * y[n-1] * (1 - y[n-1])           (logistic map, r in [3.92, 3.99])
%   f_inst[n] = f_dev * (2*y[n] - 1)           (map [0,1] -> [-f_dev, +f_dev])
%   phi_chaotic[n] = (2*pi/fs) * cumsum(f_inst[n])
%   x[n] = A * exp(j * (2*pi*fc*n/fs + phi_chaotic[n] + phi0))
%
% Field aliasing (kept for schema compatibility):
%   params.Rc    = logistic map parameter r
%   params.sigma = chaotic frequency deviation f_dev (Hz)
%   params.alpha = logistic map initial condition y0

    N  = double(spec.N);
    fs = double(spec.fs);
    t  = (0:N-1)' / fs;

    A    = params.A;
    fc   = params.fc;
    phi0 = params.phi;
    r       = params.Rc;
    f_dev   = params.sigma;
    y0      = params.alpha;
    fm      = params.fm;   % chaotic behaviour

     % Hold each chaotic value for N_hold samples (zero-order hold)
    N_hold = max(1, round(fs / fm));
    N_chaos_vals = ceil(N / N_hold);

    % Generate chaotic sequence
    y = zeros(N_chaos_vals, 1);
    y(1) = y0;
    for k = 2:N_chaos_vals
        y(k) = r * y(k-1) * (1 - y(k-1));
    end

    % Expand to N samples via zero-order hold
    y_full = repelem(y, N_hold);
    y_full = y_full(1:N);

    % Small dither to kill residual coherence
    y_full = y_full + 0.02 * randn(N, 1);

    % Map [0, 1] -> [-f_dev, +f_dev]: instantaneous frequency
    f_inst = f_dev * (2 * y_full - 1);

    % Integrate frequency to phase
    phi_chaotic = (2 * pi / fs) * cumsum(f_inst);

    % Total instantaneous phase
    phase = 2 * pi * fc * t + phi_chaotic + phi0;
    x = A * exp(1i * phase);

    % RMS normalize
    rms_val = sqrt(mean(abs(x).^2));
    assert(rms_val > 0, 'ChaoticFM: RMS is zero before normalization.');
    x_clean = x / rms_val;

    % Assertions
    assert(iscolumn(x_clean), 'Output must be a column vector.');
    assert(numel(x_clean) == spec.N, 'Output length mismatch.');
    assert(~isreal(x_clean), 'Signal must be complex.');
    assert(~all(imag(x_clean(:)) == 0), ...
        'Signal must have non-zero imaginary component.');
    assert(all(isfinite(x_clean(:))), 'Signal contains NaN/Inf.');
end