function p = init_imp_param_record()

p = struct( ...
    'impairment_seed', NaN, ...
    'snr_mode', "unset", ...
    'target_snr_db', NaN, ...
    'realized_snr_db', NaN, ...
    'noise_variance', NaN, ...
    'P_signal', NaN, ...
    'P_noise_realized', NaN, ...
    'amp_scale', NaN, ...
    'rms_out', NaN, ...
    'cfo_hz', NaN, ...
    'phase_noise_std', NaN, ...
    'delay_samp', NaN, ...
    'echo_gain_db', NaN, ...
    'rice_k_db', NaN, ...
    'channel_energy', NaN ...
);

end